In [1]:
import numpy as np

In [2]:
myarray = np.array([23,54,21,12,45,50],np.int8)

In [3]:
myarray.shape

(6,)

In [4]:
listarray =np.array([[5,6,7],[23,43,54],[23,43,21]])

In [5]:
listarray

array([[ 5,  6,  7],
       [23, 43, 54],
       [23, 43, 21]])

In [6]:
listarray.shape



(3, 3)

In [7]:
listarray.dtype


dtype('int32')

In [8]:
listarray.size

9

In [9]:
np.array({23,24,22})

array({24, 22, 23}, dtype=object)

In [10]:
zer = np.zeros((2,5))

In [11]:
zer

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
rng = np.arange(15)

In [13]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
lspace = np.linspace(1,4,21)

In [15]:

lspace

array([1.  , 1.15, 1.3 , 1.45, 1.6 , 1.75, 1.9 , 2.05, 2.2 , 2.35, 2.5 ,
       2.65, 2.8 , 2.95, 3.1 , 3.25, 3.4 , 3.55, 3.7 , 3.85, 4.  ])

In [16]:
emp = np.empty((4,6))

In [17]:
emp

array([[1.46923330e+195, 6.01347002e-154, 2.31650014e-152,
        4.25404746e+228, 2.88525110e+214, 9.62867267e+199],
       [6.01334515e-154, 1.94861607e-153, 3.29257015e+161,
        1.66077853e+243, 9.62723381e+183, 5.87331745e+294],
       [9.08367229e+223, 6.01347002e-154, 5.73818475e+180,
        4.03259187e+175, 8.54400435e-072, 6.01334434e-154],
       [1.66994701e+243, 9.75029630e+199, 1.27641000e-152,
        4.56089070e+257, 4.37630779e+156, 2.61261326e+257]])

In [18]:
emplike = np.empty_like(lspace)

In [19]:
emplike

array([1.  , 1.15, 1.3 , 1.45, 1.6 , 1.75, 1.9 , 2.05, 2.2 , 2.35, 2.5 ,
       2.65, 2.8 , 2.95, 3.1 , 3.25, 3.4 , 3.55, 3.7 , 3.85, 4.  ])

In [20]:
ide = np.identity(20)

In [21]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [22]:

ide.shape

(20, 20)

In [23]:
arr = np.arange(90)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [25]:
arr.reshape(2,45)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
        61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
        77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [26]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [27]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [28]:
ar = np.array(x)

In [29]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [31]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [33]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [34]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [35]:
ar.ndim

2

In [36]:
ar.nbytes

36

In [36]:
one = np.array([41,33,24,32,53,54,21])


In [37]:
one.argmax()

5

In [38]:
one.argmin()

6

In [39]:
one.argsort(axis=0)

array([6, 2, 3, 1, 0, 4, 5], dtype=int64)

In [40]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
one.argsort(axis=0)

array([6, 2, 3, 1, 0, 4, 5], dtype=int64)

In [42]:
ar.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [43]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [44]:
ar2 = np.array([[1,0,1],[2,1,1],[4,2,1]])

In [45]:
ar2

array([[1, 0, 1],
       [2, 1, 1],
       [4, 2, 1]])

In [46]:
ar+ar2

array([[ 2,  2,  4],
       [ 6,  6,  7],
       [11, 10, 10]])

In [47]:
ar*ar2

array([[ 1,  0,  3],
       [ 8,  5,  6],
       [28, 16,  9]])

In [48]:
arr3 = np.array([[1,4,9],[16,25,36],[49,64,81]])

In [49]:
arr3

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [50]:
np.sqrt(arr3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [51]:
np.nonzero(arr3)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [52]:
import sys

In [53]:
np_arr.itemsize*np_arr.size

NameError: name 'np_arr' is not defined

In [1]:
!pip install pyaudio


  Using cached PyAudio-0.2.11.tar.gz (37 kB)
  Running setup.py clean for pyaudio
Failed to build pyaudio
    Running setup.py install for pyaudio: started
    Running setup.py install for pyaudio: finished with status 'error'


  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\user\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-8kvgc62b\\pyaudio_78ad1e1a251e4417b0c5aee7dbb8e0d9\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-8kvgc62b\\pyaudio_78ad1e1a251e4417b0c5aee7dbb8e0d9\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\user\AppData\Local\Temp\pip-wheel-kmz37ko0'
       cwd: C:\Users\user\AppData\Local\Temp\pip-install-8kvgc62b\pyaudio_78ad1e1a251e4417b0c5aee7dbb8e0d9\
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  copying src\pyaudio.py -> build\lib.win-amd64-3.8
  running build_ext
  building '_portaudio' extension
  error: Mi